Update patch set 1
Patch Set 1:

> Build Failed
 > 
 > https://jenkins.opendaylight.org/releng/job/integration-multipatch-test-fluorine/205/
 > : FAILURE
 > 
 > Sub-project  has 1 test failures and 0 tests in error. (
 > https://jenkins.opendaylight.org/releng/job/integration-multipatch-test-fluorine/205/
 > )
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/integration-multipatch-test-fluorine/205

 > Build Failed
 > 
 > https://jenkins.opendaylight.org/releng/job/integration-multipatch-test-fluorine/205/
 > : FAILURE
 > 
 > Sub-project  has 1 test failures and 0 tests in error. (
 > https://jenkins.opendaylight.org/releng/job/integration-multipatch-test-fluorine/205/
 > )
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/integration-multipatch-test-fluorine/205

Failed tests: 
  NWUtilTest.testNegativeEtherTypeFromIpPrefix:110 expected:<[Cannot create IpAddress from 10.0.1.256]> but was:<[Supplied value "10.0.1.256" does not match required pattern "((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\p{N}\p{L}]+)?"]>

Well that doesn’t make much sense...

Patch-set: 1