LogCaptureRuleTest now shows logged errors even if test threw exception
and preserves exception thrown by test as a "suppressed", instead cause.

This makes it much clearer to find the root cause particularly in case
of errors logged by async code which cause ripple effect test failures.
For example, it took Sam a while to understand the root cause of an
https://git.opendaylight.org/gerrit/#/c/62458/ AclServiceStatefulTest
failures.  With this, it will be much clearer next time:

org.opendaylight.infrautils.testutils.LogCaptureRuleException: Expected
no error log, but: Thread terminated due to uncaught exception:
AsyncDataTreeChangeListenerBase-DataTreeChangeHandler-0
	at
org.opendaylight.infrautils.testutils.LogCaptureRule$1.lambda$0(LogCaptureRule.java:76)
	at java.util.Optional.ifPresent(Optional.java:159)
(...)
	Suppressed: org.awaitility.core.ConditionTimeoutException: Condition
with alias 'TestableListener' didn't complete within 30000 milliseconds
because org.awaitility.core.ConditionFactory.untilAtomic Callable
expected <0> but was <1>.
		at
org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:104)
		at 
(...)		
		... 16 more
Caused by:
org.opendaylight.yangtools.testutils.mockito.UnstubbedMethodException:
getInterfaceInfoFromConfigDataStore(java.lang.String interfaceName) is
not implemented in testInterfaceManager
	at
org.opendaylight.yangtools.testutils.mockito.CallsRealOrExceptionAnswer.answer(CallsRealOrExceptionAnswer.java:127)
	at
org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:93)
(...)

Change-Id: I2a5314f938d2ba364001e184b2ec07448930cd48
Signed-off-by: Michael Vorburger <vorburger@redhat.com>