Update patch set 1
Patch Set 1: Code-Review-1

Hm, this causes: "[java] Caused by: java.lang.NoSuchMethodError: edu.umd.cs.findbugs.OpcodeStack$Item.defineSpecialKind(Ljava/lang/String;)I" so looks like, despite the minor version bump, is not compatible with our version of FindBugs anymore.  We probably have to switch to SpotBugs to be able to do this bump.

Patch-set: 1
Reviewer: Gerrit User 5867 <5867@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1